on:
  push:
    branches:
      - f36
    tags:
      - tag
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install \
            rpm
      - name: Download Source
        run: |
          spectool -g *.spec
      - uses: kahenteikou/docker-mock-rpmbuilder@v1.1-p1
        env:
          SPEC_FILE: lightdm-qtquick-greeter.spec
          MOCK_CONFIG: fedora-36-x86_64
      - name: LS
        run: |
          ls -la 
      
      