on:
  push:
    branches:
      - f36
    tags:
      - tag
jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:36
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo dnf -y update
          sudo dnf -y install \
            spectool rpmdevtools \
            mock fedpkg
      - name: Download Source
        run: |
          spectool -g *.spec
      - name: ls
        run: |
          ls -la
      
      